site_name: "Search"
# site_url: https://mydomain.org/mysite
theme:
  name: "material"
  features:
    - search.highlight
    - search.share

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/lunr.js/2.3.9/lunr.min.js
  - Base_Luce.json  # Đảm bảo đường dẫn đúng
nav:
  - Home: index.md           # Trang chính
  - Présentation: Présentation.md
  - Consulter la base: Consulter_la_base.md
  - Bibliographie: Bibliographie.md